# Permalinks
permalink:              pretty
relative_permalinks:    true

# Setup
highlighter:        pygments
safe:               true
lsi:                false
encoding:           utf-8
title:              "@CodeIsGreat"
tagline:            About Code
url:                http://codeisgreat.org/
paginate:           1
baseurl:            ""
author:
  name:             Pankaj Jangid
  url:              https://twitter.com/codeisgreat
  email:            pankaj.jangid@gmail.com
