#+TITLE: ... Hello.
#+OPTIONS: toc:nil, num:nil, html-preamble:nil, html-postamble:nil, 

I am Pankaj Jangid and this is my *own* space. Follow this page to get updates from me. Usually this is more current than my twitter and fb timelines.

* Reading
  - [[https://tools.ietf.org/html/rfc6749][The OAuth 2.0 Authorization Framework]]

    Working on a tiny hello-world kind-of appication for learning something. But I don't want to re-implement authentication part. This has been done a million times by so many programmers. So I pulled a [[https://hub.docker.com/r/jboss/keycloak][Keycloak]] image from the Docker Hub. And spawned it. Great work indeed.

    But how can I just sit and watch it work. As always. Lost in the W~E~B. First [[https://www.keycloak.org/documentation][Keycloak docs]] → [[https://openid.net/connect/][OpenID]] → [[https://tools.ietf.org/html/rfc6749][OAuth]].

* To Read
  - [[https://fasterthanli.me/series/making-our-own-executable-packer/part-1][What's in a Linux executable?]]
  - [[https://openid.net/connect/][OpenID Connect]]

* Done Reading
  - [[https://taylor.gl/blog/9/][How to walk upright and stop living in a cave]]

    This is a neatly written article on indoor lighting, ventilation, humidity, temperature and other parameters that affect our lives. This is from Tylor G. Lung's blog. Go read. Some really practical and useful advices there.



