#+TITLE: Hello. I'm Pankaj Jangid
#+SUBTITLE: I read code. I write code.

This is my /*own*/ space. Follow ... oops! ... bookmark this page and
check once in a while to see what I am currently working on. Sorry if
I sound like a self-obsessed person. But there is no other place (on
the WWW) where I find it easy to write; may be because of absense of
my writing toolbox - /Emacs/. And perhaps I protect /your/ privacy in
the process 😎. If you have any comments or got a suggestion for me or
you just want to say hello to me then write an email at
_my.firstname@domain.of.this.web.site_. Or connect with me on [[https://twitter.com/jangid][Twitter]].

* [[file:notes/colors-of-web.org][Colors of Web]]
Why some designers are now using hsl() instead of rgb() for color
settings in CSS? I have tried to explain.

* [[file:notes/aws-jira-dc.org][Performance and scale testing of your App on Jira DC]]
Those who develop apps for the Atlassian Marketplace, must have come
across this requirement that their apps must meet a prescribed
performance and scalability criteria. Well, we also got this notice.

I started to explore, thinking where to start. And found that
Atlassian has very nice documentation for conducting this exercise. In
fact if you follow the guidelines religiously, you will be through
without any other help.

I have written this article to share my experience. Actually, I have
taken notes so that I can refer to it later for conducting similar
tests. I am sure you will like it.
   
* [[file:notes/emacs-macos-contacts.org][MacOS Contacts in Emacs]]
I was browsing the =etc/NEWS= file from the latest emacs source code
and found this useful feature. Currently my work requires me to work
on macOS so this is kind of essential for me to fetch contacts into
=Gnus=. Because that is what I use for all my emails and news.

Now that it is a builtin feature, no need for any extra package for
email address management and autocompletion. My online contacts book
is connected to macOS contacts via =CardDav= and now =Emacs= is also
connected to that.


