#+TITLE: ... Hello.
#+OPTIONS: toc:nil, num:nil, html-preamble:nil, html-postamble:nil, 

I am Pankaj Jangid and this is my *own* space. Follow this page to get updates from me. Usually this is more current than my twitter and fb timelines. If you have any comments or just want to say hello then write to me at my.firstname@domain.of.this.web.site.

* Recently read or currently reading
  - [[https://turnerj.com/blog/a-better-mousetrap][A Better Mousetrap]]

    This is a nice write-up on product launch journey. So many people think that it is a small thing to just try out and fail. No. Even if you are building a small /thing/, it is going to take some time. It is difficult to keep the hope alive. And the ones who do it, they really make it *big*.
    
  - [[https://lwn.net/SubscriberLink/835599/f3b49b022582e03e/][Packaging Kubernetes for Debian]]

    This arcticle clarifies why you are not seeing and perhaps won't see Kubernetes in any stable version of Debian in the near future. Debian Technical Committee (TC) will have to either change rules if they want it to bring into Debian Stable /or/ they may just keep Kubernetes in the Debian Testing repository, where they don't have any hard commitment towards security.
     
  - [[https://tools.ietf.org/html/rfc6749][The OAuth 2.0 Authorization Framework]]:
    
    Working on a tiny hello-world kind-of appication for learning something. But I don't want to re-implement authentication part. This has been done a million times by so many programmers. So I pulled a [[https://hub.docker.com/r/jboss/keycloak][Keycloak]] image from the Docker Hub. And spawned it. Great work indeed.

    But how can I just sit and watch it work. As always. Lost in the web. First [[https://www.keycloak.org/documentation][Keycloak docs]] → [[https://openid.net/connect/][OpenID]] → [[https://tools.ietf.org/html/rfc6749][OAuth]].

* Reading list
  - [[https://fasterthanli.me/series/making-our-own-executable-packer/part-1][What's in a Linux executable?]]
  - [[https://openid.net/connect/][OpenID Connect]]

* Done Reading
  - [[https://taylor.gl/blog/9/][How to walk upright and stop living in a cave]]

    This is a neatly written article on indoor lighting, ventilation, humidity, temperature and other parameters that affect our lives. This is from Tylor G. Lung's blog. Go read. Some really practical and useful advices there.



