#+TITLE: Pankaj Jangid's Writings
#+SUBTITLE: I read code. I write code.
#+OPTIONS: toc:nil, num:nil, html-postamble:nil, 
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/main.css" />

Sometimes I write.

* Writings

** [[file:notes/aws-jira-dc.html][Performance and scale testing of your App on Jira DC]]

   Those who develop apps for the Atlassian Marketplace, must have
   come across this requirement that their apps must meet a prescribed
   performance and scalability criteria. Well, we also got this
   notice.

   I started to explore, thinking where to start. And found that
   Atlassian has very nice documentation for conducting this
   exercise. In fact if you follow the guidelines religiously, you
   will be through without any other help.

   I have written this article to share my experience. Actually, I
   have taken notes so that I can refer to it later for conducting
   similar tests. I am sure you will like it.

** [[file:notes/emacs-macos-contacts.html][MacOS Contacts in Emacs]]

   I was browsing the =etc/NEWS= file from the latest emacs source
   code and found this useful feature. Currently my work requires me
   to work on macOS so this is kind of essential for me to fetch
   contacts into =Gnus=. Because that is what I use for all my emails
   and news.

   Now that it is a builtin feature, no need for any extra package for
   email address management and autocompletion. My online contacts
   book is connected to macOS contacts via =CardDav= and now =Emacs=
   is also connected to that.
